version: "3.8"
services:
  mysql:
    image: "mysql:8"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: sqlparse
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_USER: root
